# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: java

jdk:
  - oraclejdk8

#Don't build tags
branches:
  except:
  - /^v\d/

#Build and perform release (if needed)
script:
  - env
  - locale
